name: Compile Edivox Release
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Fix permissions
        run: chmod 755 pipeline/*.sh
      - name: Download compiler
        run: ./pipeline/download-compiler.sh
      - name: Compile
        run: ./pipeline/build.sh
      - name: Upload Executable
        uses: actions/upload-artifact@v1
        with:
          name: executable
          path: src/edivox.exe
  release:
    name: Release Executable
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download Executable from build
        uses: actions/download-artifact@v1
        with:
          name: executable
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Upload Release Executable
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: executable/edivox.exe
          asset_name: edivox.exe
          asset_content_type: application/octet-stream
