name: build
on: [push]
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - run: chmod 755 pipeline/*.sh
      - run: ./pipeline/download-compiler.sh
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: ./pipeline/build.sh
  upload:
    uses: actions/upload-artifact@v3
    with:
      name: executable
      path: src/edivox.exe
