name: build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Fix permissions
        run: chmod 755 pipeline/*.sh
      - name: Download compiler
        run: ./pipeline/download-compiler.sh
      - name: Compile
        run: ./pipeline/build.sh
      - name: Upload Executable
        uses: actions/upload-artifact@v1
        with:
          name: executable
          path: src/edivox.exe
